package com.eseka.physiquest.app.physics.presentation.utils

val physicsFacts = listOf(
    "A day on Venus is longer than a year on Venus.",
    "If you could fold a paper 42 times, it would reach the moon!",
    "Sound travels faster in water than in air — about 4 times faster!",
    "In space, no one can hear you scream — there's no air for sound to travel.",
    "Atoms are 99.999999999% empty space.",
    "You are constantly falling toward the Earth — gravity keeps pulling you down!",
    "Friction turns kinetic energy into heat — your hands warm up when you rub them.",
    "Without air resistance, a feather and a hammer fall at the same speed.",
    "A lightning bolt is five times hotter than the surface of the sun.",
    "The ISS orbits Earth every 90 minutes — astronauts see 16 sunrises a day.",
    "Mass and weight are not the same: weight depends on gravity, mass does not!",
    "The Large Hadron Collider is the world's biggest machine — it's 27 km long.",
    "Light can behave like both a wave and a particle — it's called wave-particle duality.",
    "You age slower on a mountain than at sea level — thanks to general relativity.",
    "Boiling water doesn't always bubble — it depends on pressure!",
    "Helium is the only element that stays liquid near absolute zero without pressure.",
    "Magnets never run out of energy — they don't \"use up\" their magnetism.",
    "Water expands when it freezes — that's why ice floats!",
    "The fastest thing in the universe? Light — nothing goes faster.",
    "Black holes warp space and time — even light can't escape.",
    "You can boil water just by lowering the air pressure — no heat required!",
    "When astronauts return to Earth, they are slightly taller for a while.",
    "The laws of physics are the same everywhere in the universe — so far!",
    "Infrared cameras can see heat — your body glows in infrared!",
    "The Doppler effect is why ambulance sirens sound different as they pass you.",
    "A moving clock ticks slower than a stationary one — time dilation is real!",
    "The center of mass is why cats always land on their feet (usually).",
    "X-rays go through skin but not bone — that's how we see your skeleton.",
    "Frictionless surfaces don't exist in reality — but they're fun in physics problems!",
    "Radio waves, microwaves, and gamma rays are all types of light.",
    "Superconductors can levitate magnets — perfect for magnetic trains!",
    "An electric eel can produce up to 600 volts — that's shocking!",
    "Nuclear fusion powers the sun — it's the opposite of nuclear fission.",
    "The Earth's magnetic field protects us from solar radiation.",
    "If you spin fast enough in space, water floats in front of you in balls.",
    "A rainbow is actually a full circle — we just usually see half of it.",
    "Tides on Earth are caused mostly by the moon's gravity.",
    "The color you see on soap bubbles is caused by light interference.",
    "Entropy is why your room gets messy — and why time moves forward.",
    "The faster you move, the heavier you become — relativistically speaking!",
    "Airplanes fly because of Bernoulli's principle and Newton's laws.",
    "Satellites stay in orbit by constantly falling — but missing the Earth.",
    "The square of the hypotenuse is still relevant — even in physics!",
    "Fire needs three things: fuel, oxygen, and heat — remove one, and it goes out.",
    "The Pascal (Pa) is a unit of pressure — 1 Pa = 1 N/m².",
    "A Newton is the force needed to accelerate 1 kg by 1 m/s².",
    "The unit of electric charge is the Coulomb — named after Charles-Augustin de Coulomb.",
    "Gamma rays can pass through lead — but not if it's thick enough!",
    "The kilogram is defined by Planck's constant since 2019.",
    "Physicists love cats — especially Schrödinger's cat, both alive and dead!",
    "Neutron stars are so dense that a teaspoonful would weigh about 6 billion tons.",
    "The Casimir effect shows that a vacuum is not empty; virtual particles can create a measurable force.",
    "Cerenkov radiation is like a sonic boom for light, occurring when a particle exceeds the speed of light in a medium.",
    "The Mpemba effect is the observation that hot water can sometimes freeze faster than cold water.",
    "Quantum entanglement describes particles linked in such a way that their fates are intertwined, no matter the distance separating them.",
    "A Galilean cannon demonstrates momentum transfer by stacking balls and dropping them, causing the top ball to launch surprisingly high.",
    "The cosmic microwave background (CMB) is the leftover radiation from the Big Bang, a faint glow that fills the universe.",
    "Dark matter doesn't interact with light, but its gravitational effects are observed in the rotation of galaxies.",
    "Dark energy is the mysterious force thought to be responsible for the accelerated expansion of the universe.",
    "The Pauli Exclusion Principle prevents electrons from occupying the same quantum state, which is why matter is stable.",
    "A quantum leap is the abrupt transition of an electron from one energy level to another, without passing through the space in between.",
    "The triple point of a substance is the specific temperature and pressure at which its solid, liquid, and gas phases can coexist in equilibrium.",
    "Sonoluminescence is the emission of light from imploding bubbles in a liquid when excited by sound.",
    "Brownian motion, the random movement of particles in a fluid, provided early evidence for the existence of atoms.",
    "The Coriolis effect, due to Earth's rotation, deflects moving objects (like winds and ocean currents) to the right in the Northern Hemisphere and to the left in the Southern.",
    "Absolute zero (0 Kelvin or -273.15°C) is the theoretical temperature at which all classical motion of particles ceases.",
    "A Bose-Einstein condensate is a state of matter where separate atoms, cooled to near absolute zero, behave as a single quantum entity.",
    "Hawking radiation is the theoretical emission of particles from near a black hole's event horizon, causing the black hole to slowly evaporate.",
    "The photoelectric effect, explained by Einstein, is the emission of electrons when light shines on a material, a key concept in quantum mechanics.",
    "Inertia is an object's resistance to any change in its state of motion. The more mass an object has, the more inertia it has.",
    "The four fundamental forces of nature are gravity, electromagnetism, the weak nuclear force, and the strong nuclear force.",
    "A 'parsec' is a unit of distance used in astronomy, equal to about 3.26 light-years.",
    "The Chandrasekhar limit is the maximum mass of a stable white dwarf star. Beyond this mass, it will collapse into a neutron star or black hole.",
    "Superfluidity is a state of matter where a fluid can flow without any viscosity, allowing it to do things like climb up the sides of a container.",
    "The Lagrangian points are positions in space where the gravitational forces of two large bodies produce enhanced regions of attraction and repulsion.",
    "A 'jiffy' is an actual unit of time, often defined as the time it takes for light to travel one centimeter in a vacuum (about 33.3 picoseconds).",
    "The Standard Model of particle physics describes the elementary particles and their interactions, but it doesn't yet include gravity.",
    "Antimatter particles have the same mass as their matter counterparts but opposite charge. When they meet, they annihilate each other in a burst of energy.",
    "The Zeeman effect is the splitting of a spectral line into several components in the presence of a static magnetic field.",
    "The Heisenberg Uncertainty Principle states that you cannot simultaneously know the exact position and momentum of a particle.",
    "A 'light-year' is a measure of distance, not time. It's the distance light travels in one year (about 9.46 trillion km).",
    "Neutrinos are incredibly light subatomic particles that pass through most matter undetected. Trillions are passing through you right now.",
    "The tensile strength of graphene is over 100 times greater than that of the strongest steel.",
    "Eddy currents are loops of electrical current induced within conductors by a changing magnetic field. They are used in braking systems on trains.",
    "Aerogel, sometimes called 'frozen smoke,' is one of the lightest solid materials known, composed of up to 99.8% air.",
    "A solar sail can propel a spacecraft by capturing the momentum of photons from the Sun.",
    "The precession of the equinoxes is the slow, conical wobble of Earth's axis of rotation, taking about 26,000 years to complete a cycle.",
    "A phonograph record works by converting the physical grooves in the vinyl into sound waves via a stylus and diaphragm.",
    "The resonance frequency is the natural vibrating frequency of an object. Applying a force at this frequency can cause a dramatic increase in amplitude, like pushing a swing.",
    "Total internal reflection is the principle behind fiber optics, where light is trapped within a glass or plastic fiber by bouncing off the inner walls.",
    "The Magnus effect explains why a spinning ball curves in the air. The spin creates a pressure difference on opposite sides of the ball.",
    "Capacitors store electrical energy in an electric field. They are a key component in most electronic circuits.",
    "Inductors store energy in a magnetic field when electric current flows through them.",
    "The Meissner effect is the expulsion of a magnetic field from a superconductor during its transition to the superconducting state.",
    "The concept of a 'wormhole' is a theoretical passage through space-time that could create shortcuts for long journeys across the universe.",
    "An 'angstrom' (Å) is a unit of length equal to 0.1 nanometers, often used to express the sizes of atoms and molecules.",
    "All the matter we can see, from stars to humans, makes up less than 5% of the universe. The rest is dark matter and dark energy.",
    "The study of sound and its properties is called acoustics.",
    "Piezoelectricity is the electric charge that accumulates in certain solid materials—such as crystals—in response to applied mechanical stress.",
    "A 'barn' is a unit of area used in nuclear physics to measure the cross-sectional area of atomic nuclei. One barn is 10⁻²⁸ m².",
    "The Hertz (Hz) is the SI unit of frequency, defined as one cycle per second. It's named after Heinrich Hertz.",
    "The Curie temperature is the temperature above which certain materials lose their permanent magnetic properties.",
    "Spaghettification is the vertical stretching and horizontal compression of objects into long thin shapes in a very strong non-homogeneous gravitational field, such as near a black hole.",
    "Wave function collapse is the process by which a quantum system's multitude of possibilities reduces to a single outcome upon measurement.",
    "Olbers' paradox asks why the night sky is dark if the universe is infinite and filled with stars. The Big Bang and the expansion of the universe provide the answer.",
    "The Roche limit is the distance within which a celestial body, held together only by its own gravity, will disintegrate due to a second celestial body's tidal forces.",
    "A Dyson sphere is a hypothetical megastructure that would encompass a star and capture a large percentage of its power output.",
    "The 'wow!' signal was a strong narrowband radio signal detected in 1977, considered by some to be a potential candidate for an extraterrestrial broadcast.",
    "The muon, a fundamental particle similar to the electron but 200 times more massive, has a surprisingly long lifetime due to time dilation when it travels near the speed of light.",
    "The first photograph of a black hole's event horizon was captured by the Event Horizon Telescope collaboration and released in 2019.",
    "The concept of 'spacetime' was introduced by Hermann Minkowski, one of Einstein's teachers, and is the fusion of three-dimensional space and one-dimensional time.",
    "Stefan-Boltzmann law states that the total energy radiated per unit surface area of a black body is directly proportional to the fourth power of the black body's thermodynamic temperature.",
    "Kirchhoff's laws for circuits, dealing with current and voltage, are fundamental to electrical engineering.",
    "The Pound-Rebka experiment in 1960 was a famous test of general relativity, demonstrating gravitational redshift with incredible precision.",
    "A Penrose diagram is a two-dimensional map of spacetime used to visualize the structure of black holes and the universe.",
    "The Planck length (about 1.6 x 10⁻³⁵ m) is the scale at which classical ideas about gravity and space-time cease to be valid.",
    "Quantum tunneling is a phenomenon where a particle can pass through a potential barrier that it classically cannot surmount. It's essential for nuclear fusion in the sun.",
    "The Biot-Savart law is an equation in electromagnetism that describes the magnetic field generated by a constant electric current.",
    "The Gibbs paradox in statistical mechanics concerns the entropy of mixing two identical gases, which is resolved by considering the indistinguishability of particles in quantum mechanics.",
    "Lenz's law states that the direction of the electric current induced in a conductor by a changing magnetic field is such that the magnetic field created by the induced current opposes the initial changing magnetic field.",
    "Faraday's law of induction describes how a changing magnetic field creates an electromotive force (or voltage).",
    "Maxwell's Equations are a set of four fundamental equations that form the foundation of classical electromagnetism, classical optics, and electric circuits.",
    "The 'ultraviolet catastrophe' was a failure of classical physics to predict the observed emission spectrum of a black body, which was resolved by Max Planck's quantum hypothesis.",
    "Symmetry in physics is a powerful concept. Noether's theorem states that for every continuous symmetry in the laws of physics, there must exist a corresponding conservation law.",
    "For example, the conservation of energy is a result of time-translation symmetry (the laws of physics don't change over time).",
    "Conservation of momentum comes from spatial-translation symmetry (the laws of physics are the same everywhere).",
    "Conservation of angular momentum arises from rotational symmetry (the laws of physics are the same no matter which way you are oriented).",
    "A 'phonon' is a quantum of vibrational mechanical energy, just as a 'photon' is a quantum of electromagnetic energy.",
    "The Lamb shift is a small difference in energy between two energy levels in the hydrogen atom, which was a key discovery in the development of quantum electrodynamics (QED).",
    "The fine-structure constant (α), approximately 1/137, is a dimensionless physical constant that characterizes the strength of the electromagnetic interaction.",
    "A Tokamak is a device that uses a powerful magnetic field to confine plasma in the shape of a torus, one of several types of magnetic confinement fusion reactors.",
    "The Aharonov-Bohm effect shows that a charged particle can be affected by an electromagnetic potential, even in a region where the magnetic and electric fields are zero.",
    "The Higgs boson is an elementary particle in the Standard Model which gives other fundamental particles, like electrons and quarks, their mass.",
    "The gravitational constant 'G' is one of the most difficult physical constants to measure accurately.",
    "A Foucault pendulum is a simple device conceived as an experiment to demonstrate the rotation of the Earth.",
    "The Mach number is the ratio of an object's speed to the speed of sound in the surrounding medium. Mach 1 is the speed of sound.",
    "When you crack a whip, the 'crack' is a small sonic boom because the tip of the whip is moving faster than the speed of sound.",
    "The term 'physics' comes from the Greek word 'physika,' which means 'natural things' or 'nature'.",
    "Archimedes' principle states that the buoyant force on a submerged object is equal to the weight of the fluid that the object displaces.",
    "Pascal's law states that a pressure change at any point in a confined incompressible fluid is transmitted throughout the fluid such that the same change occurs everywhere.",
    "The Bernoulli effect is responsible for the lift generated by an airplane wing, but Newton's third law (action-reaction) is equally important.",
    "The Leidenfrost effect is seen when a liquid, in near contact with a mass significantly hotter than the liquid's boiling point, produces an insulating vapor layer that keeps the liquid from boiling rapidly.",
    "A 'worm' in physics is a type of defect in a crystal lattice.",
    "The Rayleigh-Taylor instability occurs at the interface between two fluids of different densities when the lighter fluid is pushing the heavier fluid.",
    "Plasma is the most common state of matter in the universe, making up the sun and other stars.",
    "The Poynting vector represents the directional energy flux density (the rate of energy transfer per unit area) of an electromagnetic field.",
    "A 'graybody' is an object that absorbs a constant fraction of the electromagnetic radiation that falls on it, at all wavelengths. A 'blackbody' is the ideal case where the fraction is 1.",
    "The specific heat capacity of a substance is the amount of heat energy required to raise the temperature of one unit of mass of the substance by one degree Celsius.",
    "Water has a very high specific heat capacity, which is why it's used as a coolant and why coastal areas have more moderate climates.",
    "Latent heat is the energy released or absorbed by a body during a constant-temperature process, such as a phase change.",
    "The concept of 'action' in physics is a quantity that can be used to derive the equations of motion of a system through the principle of least action.",
    "Feynman diagrams are pictorial representations of the mathematical expressions describing the interactions of subatomic particles.",
    "The 'spin' of a particle is an intrinsic form of angular momentum, but it doesn't mean the particle is literally spinning like a top.",
    "The geodetic effect is the effect of the curvature of spacetime, predicted by general relativity, on a vector carried along with an orbiting body.",
    "Frame-dragging is an effect on spacetime, predicted by general relativity, that is due to a rotating massive object.",
    "The cosmic distance ladder is the succession of methods by which astronomers determine the distances to celestial objects.",
    "Standard candles are astronomical objects that have a known absolute magnitude, which allows their distance to be calculated from their observed brightness.",
    "Type Ia supernovae are important standard candles for measuring cosmological distances because they all have nearly the same peak luminosity.",
    "The 'Great Attractor' is a gravitational anomaly in intergalactic space, a region of space that appears to be pulling our galaxy and many others towards it.",
    "The Hubble constant (H₀) describes the rate at which the universe is expanding. Its precise value is still a subject of active research.",
    "Quantum chromodynamics (QCD) is the theory of the strong interaction between quarks and gluons, the fundamental particles that make up composite hadrons such as the proton and neutron.",
    "Quark confinement is the phenomenon that quarks and gluons cannot be isolated; they are confined within composite particles (hadrons).",
    "A 'plasmon' is a quantum of plasma oscillation, where the electrons in a metal oscillate collectively.",
    "The Raman effect, discovered by C. V. Raman, is the inelastic scattering of a photon by a molecule which is excited to higher vibrational or rotational energy levels.",
    "Magnetic monopoles, hypothetical particles that are isolated magnets with only one magnetic pole, have been predicted by some theories but have never been observed.",
    "The Sun loses about 4 million tons of mass every second due to nuclear fusion (E=mc^2).",
    "A 'tokamak' is a doughnut-shaped machine for producing controlled nuclear fusion.",
    "The Kelvin (K) is the base unit of temperature in the International System of Units (SI). Unlike Celsius and Fahrenheit, it is not expressed in 'degrees'.",
    "Harmonics in music are a direct application of the physics of standing waves on a string or in a column of air.",
    "The twinkling of stars is caused by the refraction of starlight as it passes through Earth's turbulent atmosphere.",
    "Polarized sunglasses work by blocking glare, which is horizontally polarized light, using a filter that only allows vertically polarized light to pass through.",
    "The blue color of the sky is due to Rayleigh scattering, where shorter (blue) wavelengths of light are scattered more effectively by the molecules in the atmosphere than longer (red) wavelengths.",
    "Sunsets appear red because the sunlight has to pass through more of the atmosphere, scattering away most of the blue light and leaving the red light to reach our eyes.",
    "The gravitational pull of the Sun and Moon can cause slight deformations in the Earth's solid surface, known as 'Earth tides'.",
    "A pendulum clock will run slightly slower at the equator than at the poles because gravity is slightly weaker at the equator due to the Earth's rotation and bulge.",
    "The term 'quantum' was coined by Max Planck in 1900.",
    "Emmy Noether, a brilliant mathematician, proved two theorems that are fundamental to modern physics, linking symmetry and conservation laws.",
    "Paul Dirac's equation predicted the existence of antimatter before it was ever observed.",
    "Richard Feynman was not only a Nobel laureate but also a renowned lecturer and amateur artist.",
    "Marie Curie was the first woman to win a Nobel Prize, the first person to win it twice, and the only person to win it in two different scientific fields (Physics and Chemistry).",
    "Lise Meitner was a key physicist who first explained nuclear fission, but she was overlooked by the Nobel committee.",
    "The inverse square law applies to many phenomena in physics, including gravity, electrostatic force, and the intensity of light and sound.",
    "A 'wormhole' is a speculative structure linking disparate points in spacetime, and is a solution to the Einstein field equations.",
    "The 'no-hair theorem' in general relativity postulates that a black hole is characterized by only three parameters: mass, charge, and angular momentum.",
    "An 'ergosphere' is a region outside a rotating black hole's event horizon where it is impossible to stand still.",
    "The 'Penrose process' is a theoretical method to extract energy from a rotating black hole.",
    "A 'white hole' is the theoretical time reversal of a black hole. While allowed by general relativity, their existence is considered highly unlikely.",
    "The 'cosmological principle' is the assumption that the universe is homogeneous and isotropic on large scales, meaning it looks the same everywhere and in every direction.",
    "The 'Bekenstein bound' is an upper limit on the entropy that can be contained in a finite region of space which has a finite amount of energy.",
    "A 'gravitational lens' is a distribution of matter (such as a galaxy cluster) between a distant light source and an observer, that is capable of bending the light from the source as the light travels towards the observer.",
    "The 'Shapiro delay' is a test of general relativity, where radar signals passing near a massive object take slightly longer to travel to a target and longer to return than they would if the mass of the object were not present.",
    "The 'Pioneer anomaly' was the observed deviation from predicted accelerations of the Pioneer 10 and 11 spacecraft, which was later explained by thermal radiation effects.",
    "The 'flyby anomaly' is an unexpected energy increase observed during Earth flybys of some spacecraft. Its cause is still a subject of debate.",
    "The Zeno effect in quantum mechanics is where an unstable particle, if observed continuously, will never decay.",
    "The 'Unruh effect' is the prediction that an accelerating observer will observe black-body radiation where an inertial observer would observe none.",
    "The 'Higgs field' is a theoretical energy field that is thought to exist everywhere in the universe. The Higgs boson is a manifestation of this field.",
    "A 'tachyon' is a hypothetical particle that always travels faster than light. Its existence would violate causality, and it has not been found.",
    "The 'de Broglie wavelength' is the wavelength associated with a massive particle, confirming the wave-particle duality of matter.",
    "The 'Compton effect' is the decrease in energy (increase in wavelength) of an X-ray or gamma ray photon, when it is scattered by an electron.",
    "A 'phonon' is a collective excitation in a periodic, elastic arrangement of atoms or molecules in condensed matter, like a quantum of sound.",
    "A 'magnon' is a collective excitation of the electrons' spin structure in a crystal lattice.",
    "A 'polariton' is a hybrid light-matter quasiparticle that arises from the strong coupling of electromagnetic waves with an electric or magnetic dipole-carrying excitation.",
    "The 'Kondo effect' in condensed matter physics describes the scattering of conduction electrons in a metal due to magnetic impurities.",
    "A 'Wigner crystal' is a solid phase of electrons that can form when their kinetic energy is much smaller than their electrostatic repulsive energy.",
    "A 'Faraday cage' is an enclosure used to block electromagnetic fields.",
    "The 'skin effect' is the tendency of an alternating electric current (AC) to become distributed within a conductor such that the current density is largest near the surface of the conductor.",
    "The 'Hall effect' is the production of a voltage difference (the Hall voltage) across an electrical conductor, transverse to an electric current in the conductor and a magnetic field perpendicular to the current.",
    "The 'quantum Hall effect' is a quantum-mechanical version of the Hall effect, observed in two-dimensional electron systems subjected to low temperatures and strong magnetic fields.",
    "The 'Josephson effect' is a phenomenon that occurs when two superconductors are placed in close proximity, with a thin insulating barrier between them.",
    "The 'g-factor' is a dimensionless quantity that characterizes the magnetic moment and angular momentum of an atom, a particle or the nucleus.",
    "The 'Lamb-dip' is a sharp feature in the absorption or emission spectrum of a gas, used for frequency stabilization in lasers.",
    "The 'Bragg's law' gives the angles for coherent and incoherent scattering from a crystal lattice.",
    "A 'metamaterial' is a material engineered to have a property that is not found in naturally occurring materials, such as a negative refractive index.",
    "The 'Doppler cooling' technique is used to cool atoms by using laser light.",
    "An 'optical tweezer' uses a highly focused laser beam to hold and move microscopic objects, like atoms or cells.",
    "The 'Sagnac effect' is a phenomenon encountered in interferometry that is elicited by rotation, used in devices like ring laser gyroscopes.",
    "The 'Goos-Hänchen effect' is an optical phenomenon in which linearly polarized light undergoes a small lateral shift when totally internally reflected.",
    "The 'Pockels effect' describes the change in the refractive index of a medium caused by an electric field.",
    "The 'Kerr effect' is a similar phenomenon where the change in refractive index is proportional to the square of the electric field.",
    "A 'bolometer' is a sensitive instrument for measuring radiant energy, especially infrared radiation.",
    "A 'calorimeter' is an object used for calorimetry, or the process of measuring the heat of chemical reactions or physical changes as well as heat capacity.",
    "The 'adiabatic process' is one that occurs without transfer of heat or matter between a thermodynamic system and its surroundings.",
    "An 'isobaric process' is a thermodynamic process in which the pressure stays constant.",
    "An 'isochoric process' is a thermodynamic process in which the volume of the closed system undergoing such a process remains constant.",
    "An 'isothermal process' is a thermodynamic process in which the temperature of the system remains constant.",
    "The 'Carnot cycle' represents the most efficient heat engine cycle allowed by physical laws.",
    "The 'Stirling engine' is a heat engine that is operated by a cyclic compression and expansion of air or other gas (the working fluid) at different temperatures.",
    "The 'Peltier effect' is the presence of heating or cooling at an electrified junction of two different conductors.",
    "The 'Seebeck effect' is the conversion of heat directly into electricity at the junction of different types of wire.",
    "The 'Thomson effect' describes the heating or cooling of a current-carrying conductor with a temperature gradient.",
    "A 'heat pipe' is a heat-transfer device that combines the principles of both thermal conductivity and phase transition to efficiently manage heat.",
    "The 'Reynolds number' is a dimensionless quantity in fluid mechanics that helps predict flow patterns in different fluid flow situations.",
    "The 'Prandtl number' is a dimensionless number approximating the ratio of momentum diffusivity to thermal diffusivity.",
    "The 'Navier-Stokes equations' are the fundamental equations that describe the motion of viscous fluid substances.",
    "The 'Euler equations' govern the motion of a compressible, inviscid fluid.",
    "The 'Poiseuille's law' relates the pressure drop, viscosity, and dimensions of a pipe to the flow rate of the fluid through it.",
    "The 'Venturi effect' is the reduction in fluid pressure that results when a fluid flows through a constricted section (or choke) of a pipe.",
    "The 'hydraulic jump' is a phenomenon in the science of hydraulics which is frequently observed in open channel flow such as rivers and spillways.",
    "The 'cavitation' is the formation of vapor cavities in a liquid – i.e. small liquid-free zones ('bubbles' or 'voids') – that are the consequence of forces acting upon the liquid.",
    "The 'surface tension' is the tendency of liquid surfaces to shrink into the minimum surface area possible.",
    "The 'elasticity' of a material is its ability to resist a distorting influence and to return to its original size and shape when that influence or force is removed.",
    "The 'plasticity' of a material is its ability to undergo permanent deformation, a non-reversible change of shape in response to applied forces.",
    "The 'yield strength' of a material is the stress at which a material begins to deform plastically.",
    "The 'ultimate tensile strength' is the maximum stress that a material can withstand while being stretched or pulled before breaking.",
    "The 'fatigue' is the weakening of a material caused by cyclic loading that results in progressive and localized structural damage.",
    "The 'creep' is the tendency of a solid material to move slowly or deform permanently under the influence of persistent mechanical stresses.",
    "The 'damping' is an influence within or upon an oscillatory system that has the effect of reducing, restricting or preventing its oscillations.",
    "A 'gyroscope' is a device used for measuring or maintaining orientation and angular velocity.",
    "The 'moment of inertia' is the rotational analog of mass for linear motion.",
    "The 'angular momentum' is the rotational equivalent of linear momentum.",
    "The 'torque' is the rotational equivalent of linear force.",
    "A 'flywheel' is a mechanical device specifically designed to efficiently store rotational energy.",
    "The 'work-energy theorem' states that the work done by all forces acting on a particle equals the change in the particle's kinetic energy.",
    "The 'impulse-momentum theorem' states that the impulse applied to an object is equal to the change in its momentum.",
    "A 'ballistic pendulum' is a device for measuring the momentum of a projectile, from which it is possible to calculate the velocity and kinetic energy.",
    "The 'coefficient of restitution' is a measure of the 'bounciness' of a collision between two objects.",
    "An 'inelastic collision' is one in which kinetic energy is not conserved due to the action of internal friction.",
    "An 'elastic collision' is one in which there is no net loss in kinetic energy in the system as a result of the collision.",
    "The 'center of percussion' is the point on a bat, racket, or other extended object where a perpendicular impact will produce no reactive shock at the pivot.",
    "The 'sweet spot' on a tennis racket is related to the center of percussion.",
    "The 'escape velocity' from Earth is about 11.2 kilometers per second (about 40,320 km/h).",
    "The 'orbital velocity' for a low Earth orbit is about 7.8 kilometers per second (about 28,000 km/h).",
    "A 'geostationary orbit' is a circular geosynchronous orbit 35,786 kilometres (22,236 miles) above Earth's equator and following the direction of Earth's rotation.",
    "A 'Lagrange point' is a location in space where the combined gravitational forces of two large bodies, such as Earth and the sun or Earth and the moon, equal the centrifugal force felt by a much smaller third body.",
    "The 'Alcubierre drive' is a speculative idea for a faster-than-light spacecraft, based on a solution of Einstein's field equations in general relativity.",
    "The 'Kardashev scale' is a method of measuring a civilization's level of technological advancement based on the amount of energy it is able to use.",
    "The 'Fermi paradox' is the apparent contradiction between the lack of evidence for extraterrestrial civilizations and various high estimates for their probability.",
    "The 'Drake equation' is a probabilistic argument used to arrive at an estimate of the number of active, communicative extraterrestrial civilizations in the Milky Way galaxy.",
    "The 'anthropic principle' is the philosophical consideration that observations of the universe must be compatible with the conscious and sapient life that observes it.",
    "The 'multiverse' is a hypothetical group of multiple universes. Together, these universes comprise everything that exists: the entirety of space, time, matter, energy, information, and the physical laws and constants that describe them.",
    "The 'string theory' is a theoretical framework in which the point-like particles of particle physics are replaced by one-dimensional objects called strings.",
    "The 'M-theory' is a theory in physics that unifies all consistent versions of superstring theory.",
    "The 'loop quantum gravity' is a theory of quantum gravity, which aims to merge quantum mechanics and general relativity.",
    "The 'causal dynamical triangulation' is an approach to quantum gravity that is independent of string theory.",
    "A 'phonon' is also known as a quantized sound wave.",
    "The study of the flow of matter, primarily in a liquid state, but also as 'soft solids' or solids under conditions in which they respond with plastic flow rather than deforming elastically in response to an applied force is called rheology.",
    "Thixotropy is the property of some non-Newtonian fluids to show a time-dependent change in viscosity; the longer the fluid undergoes shear stress, the lower its viscosity. Ketchup is a common example.",
    "Dilatant or shear-thickening fluids increase their viscosity with the rate of shear strain. A mixture of cornstarch and water is a classic example.",
    "The Weissenberg effect is a phenomenon that occurs when a rotating rod is inserted into a solution of an elastic polymer. The fluid will be drawn up the rod, against gravity.",
    "The phenomenon of 'supercooling' allows a liquid to be cooled below its freezing point without becoming solid.",
    "Glass is an amorphous solid, not a slow-moving liquid. The myth that stained glass in old churches is thicker at the bottom due to flow is false.",
    "The sun's corona is much hotter than its surface (photosphere) - millions of degrees Celsius compared to about 5,500 °C. The reason for this is still an active area of research.",
    "The aurora borealis and aurora australis are caused by charged particles from the sun colliding with atoms in Earth's upper atmosphere.",
    "Every lightning bolt creates ozone, thus helping to protect the planet from ultraviolet radiation.",
    "Static electricity can build up to tens of thousands of volts, but the current is usually very low, which is why it's not always dangerous.",
    "The human eye can detect a single photon.",
    "The Casimir effect predicts that two uncharged, parallel plates in a vacuum will experience an attractive force due to quantum vacuum fluctuations.",
    "The 'quantum foam' is a concept in quantum gravity, describing the fabric of spacetime at the tiniest scales as a seething, turbulent realm of changing geometries.",
    "A 'white dwarf' is the stellar remnant composed mostly of electron-degenerate matter. It's the final evolutionary state of stars whose mass is not high enough to become a neutron star.",
    "The process that powers a 'nova' is the sudden reignition of nuclear fusion on the surface of a white dwarf in a binary system.",
    "A 'supernova' is a powerful and luminous stellar explosion. A star's death.",
    "A 'hypernova' or 'collapsar' is a type of supernova explosion with an energy substantially higher than standard supernovae and is considered a possible source of long-duration gamma-ray bursts.",
    "The 'r-process' (rapid neutron-capture process) is a set of nuclear reactions that in nuclear astrophysics is responsible for the creation of approximately half of the atomic nuclei heavier than iron, believed to occur in supernova explosions or neutron star mergers.",
    "The 's-process' (slow neutron-capture process) is the other major process for creating heavy elements, occurring in stars with a low to intermediate mass.",
    "The 'proton-proton chain' is one of the two known sets of nuclear fusion reactions by which stars convert hydrogen to helium. It dominates in stars the size of the Sun or smaller.",
    "The 'CNO cycle' (Carbon-Nitrogen-Oxygen cycle) is the other process of stellar hydrogen-to-helium fusion, and it is the dominant source of energy in stars more massive than about 1.3 times the mass of the Sun.",
    "Helioseismology is the study of the structure and dynamics of the Sun through its oscillations.",

    // Adding the final 69 facts to complete 366
    "The photoelectric effect proves that light has particle-like properties - Einstein won the Nobel Prize for this discovery, not relativity!",
    "Quarks come in six 'flavors': up, down, strange, charm, bottom, and top - physicists have a sense of humor!",
    "The Chandrasekhar limit of 1.4 solar masses determines whether a star becomes a white dwarf or explodes as a supernova.",
    "Quantum superposition means a particle can be in multiple states simultaneously until observed - like Schrödinger's famous cat.",
    "The weak nuclear force is responsible for radioactive decay and is weaker than electromagnetism but stronger than gravity.",
    "Gravitational time dilation means time runs slower in stronger gravitational fields - GPS satellites must account for this!",
    "The cosmic web is the largest-scale structure of the universe, with galaxies connected by filaments of dark matter.",
    "Baryonic matter (normal matter made of protons and neutrons) makes up only about 4.9% of the total mass-energy of the universe.",
    "The speed of light in a vacuum is exactly 299,792,458 meters per second - this defines the meter!",
    "Virtual particles constantly pop in and out of existence in the quantum vacuum, borrowing energy from the universe briefly.",
    "The strong nuclear force has a property called 'asymptotic freedom' - quarks become more tightly bound when pulled apart.",
    "Neutron degeneracy pressure prevents neutron stars from collapsing further - it's a quantum mechanical effect.",
    "The cosmological constant problem is one of physics' biggest mysteries - why is dark energy's density so small?",
    "Magnetic flux quantization in superconductors shows that magnetic field lines can only penetrate in discrete amounts.",
    "The Berry phase is a quantum mechanical phase acquired when a system undergoes a cyclic evolution.",
    "Topological insulators conduct electricity on their surface but are insulators in their bulk.",
    "The quantum Zeno effect can freeze the evolution of a quantum system by frequent measurements.",
    "Phononic crystals can control sound waves the same way photonic crystals control light waves.",
    "The Aharonov-Casher effect is the magnetic dual of the Aharonov-Bohm effect, involving magnetic dipoles.",
    "Squeezed light has reduced quantum noise in one property at the expense of increased noise in another.",
    "The Unruh temperature is the temperature an accelerating observer experiences due to quantum field fluctuations.",
    "Majorana fermions are their own antiparticles and could be used for topological quantum computing.",
    "The quantum spin Hall effect occurs in topological insulators with strong spin-orbit coupling.",
    "Anyons are exotic particles that exist only in two dimensions and have fractional statistics.",
    "The Efimov effect predicts an infinite series of three-body bound states for certain particle interactions.",
    "Quantum dots are semiconductor nanocrystals that confine electrons in all three spatial dimensions.",
    "The fractional quantum Hall effect reveals exotic collective states of electrons in strong magnetic fields.",
    "Polaron formation occurs when an electron in a crystal deforms the surrounding lattice structure.",
    "The Kondo temperature characterizes the energy scale below which the Kondo effect becomes important.",
    "Spin ice materials have frustrated magnetic interactions that mimic the proton disorder in water ice.",
    "The quantum anomalous Hall effect occurs without an external magnetic field in certain materials.",
    "Weyl semimetals have exotic electronic properties including surface states called Fermi arcs.",
    "The Kibble mechanism explains how topological defects form during phase transitions in the early universe.",
    "Holographic duality suggests that a volume of space can be represented as information on its boundary.",
    "The black hole information paradox questions whether information falling into a black hole is destroyed.",
    "AdS/CFT correspondence is a theoretical tool linking gravity theories to quantum field theories.",
    "The firewall paradox suggests that black hole event horizons might be walls of high-energy particles.",
    "Emergent gravity theories propose that gravity arises from more fundamental microscopic interactions.",
    "The weak gravity conjecture suggests that gravity is always the weakest force in any consistent theory.",
    "Swampland conjectures attempt to distinguish which quantum field theories can be coupled to gravity.",
    "The hierarchy problem asks why the weak nuclear force is so much stronger than gravity.",
    "Technicolor theories propose that the Higgs mechanism arises from new strong interactions.",
    "Extra dimensions might be compactified on tiny scales, invisible to our everyday experience.",
    "The landscape problem in string theory suggests there might be 10^500 possible universes.",
    "Cosmic inflation explains why the universe is so uniform and geometrically flat on large scales.",
    "The multiverse hypothesis suggests our universe is one of many, possibly infinite, universes.",
    "The measure problem in cosmology asks how to assign probabilities to different observations in an infinite multiverse.",
    "Eternal inflation predicts that inflation continues forever in most regions of spacetime.",
    "The Big Rip is a hypothetical scenario where dark energy eventually tears apart all matter.",
    "Heat death is the theoretical final state of the universe when entropy reaches its maximum.",
    "Proton decay, if it occurs, would mean that even protons are not permanent - the universe would eventually contain only leptons and photons.",
    "The Planck epoch refers to the first 10^-43 seconds after the Big Bang when quantum gravity effects dominated.",
    "Baryogenesis explains how the universe developed an excess of matter over antimatter.",
    "The electroweak epoch was when the electromagnetic and weak nuclear forces were unified.",
    "Big Bang nucleosynthesis produced the light elements hydrogen, helium, and lithium in the first few minutes.",
    "The cosmic microwave background shows tiny temperature fluctuations that seeded all cosmic structure.",
    "Dark matter halos provide the gravitational scaffolding on which galaxies and galaxy clusters form.",
    "The coincidence problem asks why dark energy density is comparable to matter density today.",
    "Vacuum metastability suggests our universe might be in a false vacuum that could decay.",
    "The fine-tuning problem notes that small changes in physical constants would make life impossible.",
    "Anthropic reasoning attempts to explain fine-tuning by considering observer selection effects.",
    "The holographic principle suggests that the information in a volume can be encoded on its boundary.",
    "Black hole thermodynamics relates a black hole's area to its entropy and temperature.",
    "The no-cloning theorem proves that arbitrary quantum states cannot be perfectly copied.",
    "Quantum error correction protects quantum information from decoherence and other noise.",
    "Topological quantum computing uses anyons to perform calculations that are naturally error-resistant.",
    "The Church-Turing-Deutsch principle extends computability to include quantum mechanical processes.",
    "Bell's theorem proves that local hidden variable theories cannot reproduce all quantum mechanical predictions.",
    "Quantum nonlocality allows entangled particles to exhibit correlations stronger than any classical theory permits.",
)