package com.eseka.physiquest.core.domain.utils

enum class FirebaseAuthError : Error {
    INVALID_EMAIL,
    USER_NOT_FOUND,
    WRONG_PASSWORD,
    EMAIL_ALREADY_IN_USE,
    WEAK_PASSWORD,
    NETWORK_ERROR,
    TOO_MANY_REQUESTS,
    OPERATION_NOT_ALLOWED,
    ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL,
    CREDENTIAL_ALREADY_IN_USE,
    INVALID_CREDENTIAL,
    GOOGLE_SIGN_IN_FAILED,
    USER_DISABLED,
    REQUIRES_RECENT_LOGIN,
    INVALID_LINK,
    USER_TOKEN_EXPIRED,
    INVALID_USER_TOKEN,
    USER_NOT_SIGNED_IN,
    SESSION_EXPIRED,
    QUOTA_EXCEEDED,
    UNAUTHORIZED_DOMAIN,
    INVALID_PHOTO_URL,
    FAILED_REAUTHENTICATION,
    CREDENTIAL_CREATION_ERROR,
    CREDENTIAL_FETCHING_ERROR,
    IMAGE_UPLOAD_FAILED,
    IMAGE_DELETE_FAILED,
    UNKNOWN
}

enum class FirebaseFirestoreError : Error {
    CANCELLED,
    UNKNOWN,
    INVALID_ARGUMENT,
    NETWORK_ERROR,
    DEADLINE_EXCEEDED,
    NOT_FOUND,
    ALREADY_EXISTS,
    PERMISSION_DENIED,
    RESOURCE_EXHAUSTED,
    FAILED_PRECONDITION,
    ABORTED,
    OUT_OF_RANGE,
    UNIMPLEMENTED,
    INTERNAL,
    UNAVAILABLE,
    DATA_LOSS,
    UNAUTHENTICATED
}

enum class FirebaseStorageError : Error {
    UNKNOWN,
    OBJECT_NOT_FOUND,
    BUCKET_NOT_FOUND,
    PROJECT_NOT_FOUND,
    QUOTA_EXCEEDED,
    NOT_AUTHENTICATED,
    NOT_AUTHORIZED,
    RETRY_LIMIT_EXCEEDED,
    INVALID_CHECKSUM,
    CANCELED,
    NETWORK_ERROR,
    IO_ERROR
}

